export function Header() {
  return (
    <header className="sticky top-0 z-20 border-b border-slate-800 bg-slate-950/70 backdrop-blur">
      <div className="mx-auto flex w-full max-w-6xl items-center justify-between px-6 py-4">
        <div>
          <p className="text-sm font-semibold uppercase tracking-wide text-slate-300">Code Origin Detector</p>
          <p className="text-xs text-slate-400">Estimate whether code snippets were written by humans or generated by AI.</p>
        </div>
        <span className="rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-300">Prototype</span>
      </div>
    </header>
  );
}
